name: portfolio
description: Yousef Abu Hzian - Flutter Developer Portfolio
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.0
  universal_html: ^2.3.0
  url_launcher: ^6.3.0
  visibility_detector: ^0.4.0+2

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/

  fonts:
    - family: SpaceGrotesk
      fonts:
        - asset: assets/fonts/SpaceGrotesk-Regular.ttf
        - asset: assets/fonts/SpaceGrotesk-Medium.ttf
          weight: 500
        - asset: assets/fonts/SpaceGrotesk-Bold.ttf
          weight: 700

    - family: Inter
      fonts:
        - asset: assets/fonts/Inter_28pt-Regular.ttf
        - asset: assets/fonts/Inter_28pt-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter_28pt-Bold.ttf
          weight: 700
